name: Deploy to Heroku

on:
  workflow_run:
    workflows: [ "Build" ]
    branches: [ master ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # TODO: release before deploying

      - name: Push to Heroku
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_email: lukaszjedryczka.biuro@gmail.com
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}


